name = "example"
perm = "default"
rows = 3
title = "&dVelocityGUI"
empty = "GREEN_STAINED_GLASS_PANE"
sound = "ENTITY_ARROW_HIT_PLAYER"
commands = [
  "rules",
  "version",
  "plugins",
  "help",
  "pl"
]

[items]
[items.13]
material = "OAK_SIGN"
stack = 1
name = "&dVelocityGUI"
lore = [
  "&eA Velociy Side GUI",
  "&eFor all your servers"
]
enchanted = true
commands = [
  "sudo= I love VelocityGUI"
]